name: pingbox
description: PingBox
version: 1.0.0+2
publish_to: none

environment:
    sdk: ^3.5.0

dependencies:
    bloc: ^8.1.4
    connectivity_plus: ^6.1.4
    cupertino_icons:
    curl_logger_dio_interceptor: ^1.0.0
    dartz: ^0.10.1
    dio: ^5.3.2
    equatable: ^2.0.5
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.6
    flutter_localizations:
        sdk: flutter
    flutter_secure_storage:
    freezed_annotation: ^2.4.1
    get_it: ^7.6.4
    handy_extensions: ^0.2.18
    injectable: ^2.3.2
    intl: ^0.19.0
    json_annotation: ^4.9.0
    jwt_decode: ^0.3.1
    modal_bottom_sheet: ^3.0.0-pre
    network_info_plus: ^4.0.2
    package_info_plus: ^8.0.2
    path: ^1.8.0
    path_provider:
    permission_handler:
    pretty_dio_logger: ^1.3.1
    relative_scale: ^2.0.0
    sentry_dio: ^8.14.2
    sentry_flutter: ^8.14.2
    sentry_logging: ^8.14.2
    shared_preferences: ^2.2.2

dev_dependencies:
    build_runner: ^2.4.6
    flutter_native_splash: ^2.3.2
    flutter_test:
        sdk: flutter
    freezed: ^2.4.2
    injectable_generator:
    json_serializable: ^6.7.1
    mocktail: ^1.0.4
    very_good_analysis: ^7.0.0

flutter:
    uses-material-design: true
    generate: true


    fonts:
        - family: "IBM Plex Mono"
          fonts:
              - asset: fonts/IBMPlexMono-Thin.ttf
                weight: 100
              - asset: fonts/IBMPlexMono-ExtraLight.ttf
                weight: 200
              - asset: fonts/IBMPlexMono-Light.ttf
                weight: 300
              - asset: fonts/IBMPlexMono-Regular.ttf
                weight: 400
              - asset: fonts/IBMPlexMono-Medium.ttf
                weight: 500
              - asset: fonts/IBMPlexMono-SemiBold.ttf
                weight: 600
              - asset: fonts/IBMPlexMono-Bold.ttf
                weight: 700
